baseURL = 'https://godot-japan.com/'
languageCode = 'ja-jp'
defaultContentLanguage = 'ja'
title = 'Godot Japan'
theme = 'GodotJapan2024'
enableGitInfo = true
ignoreLogs = ['error-remote-getjson']

[params]
defaultNoImage = "/images/m_e_other_501.png"
imageQuality = 75
recaptchaKey = "6Ley6EoqAAAAADEselvCBRRULPXMU11Z3K4kyiPd"

[imaging]
quality = 75
resampleFilter = "Lanczos"
anchor = "Smart"

[caches]
  [caches.getjson]
    maxAge = "1h"
  [caches.getresource]
    maxAge = "1h"

[mediaTypes]
  [mediaTypes.'text/json']
    suffixes = ['json']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = false
      block = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keyword"
    weight = 100

  [[related.indices]]
    name = "tags"
    weight = 80

[languages]
  [languages.ja]
    languageCode = "ja-JP"
    languageName = "日本語"
    weight = 1
    title = "Godot Japan"
    [languages.ja.params]
      description = "Godotエンジンの日本コミュニティサイト"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.134.0"

  [[related.indices]]
    name = "date"
    weight = 10